### ISSUE TITLE
Issue with docker-compose v3, bin/plugin: command not found

### ISSUE THREAD

**Issue by Laudenlaruto** [evnsio/grav#3]
I try lauching this image with docker-compose 3:
```
version: '3'
services:
  site:
    image: evnsio/grav
    container_name: grav
    restart: always
    ports:
      - 8080:80
    environment:
      ADMIN_USER: admin
      ADMIN_PASSWORD: Pa55word
      ADMIN_EMAIL: admin@example.com
      ADMIN_PERMISSIONS: b
      ADMIN_FULLNAME: Admin
      ADMIN_TITLE: SiteAdmin
      
    volumes:
      - /docker/grav/data:/var/www/grav-admin/
      - /docker/grav/config:/user/config:rw
```
I get the following error:

```
Creating grav ... 
Creating grav ... done
Attaching to grav
grav    | [ INFO ] Setting up Grav admin user
grav    | sudo: bin/plugin: command not found
grav exited with code 1
```
Any ideas?

**Comment by Laudenlaruto** [comment]
Okay  the problem is this lines:
volumes:
      - /docker/grav/data:/var/www/grav-admin/

It didn't want to install grav on that volume if I added it as a volume... I tried putting rw. I ended up deleting the line.
That means I can't access files through my host and neither have persistent data... I'm looking for a work around.

**Comment by chasgames** [comment]
i have same issue.. 

I mounted the backup directory instead and just take backups.
on the host:
```sudo chown -R 33:33 backup```

then changed the docker-compose

```
version: '2'
services:
  site:
    image: evns/grav
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=Pa55word
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PERMISSIONS=b
      - ADMIN_FULLNAME=Admin
      - ADMIN_TITLE=SiteAdmin
      - DOMAIN=example.com # set to your root/apex domain
      - GENERATE_CERTS=false # set to true to automatically setup trusted ssl with let's encrypt
    volumes:
      - /backup:/var/www/grav-admin/backup
volumes:
  backup:
    external: false
```
